### ISSUE TITLE
[Dev] Cooking 프로젝트 관련 초기 설정 및 문서화 작업 진행 

### ISSUE THREAD

**Issue by Bumnote** [Bumnote/catchTable#10]
### 📝 작업 내용 및 설명 
<hr>

Cooking 프로젝트를 진행함에 있어 자동화 작업을 진행하려고 합니다. CI(지속적인 통합)를 통하여 Push 또는 PR 발생 시 자동으로 Build 할 수 있는 작업과 Issue와 PR 템플릿을 만들어 문서 작성을 자동화하는 작업입니다. 이를 통하여 보다 더 편리한 개발 환경을 구축하는 것이 목표입니다.

### ✔️ TO-DO
<hr>

- [x] CI 작업 진행  (Build 기능만)
- [x] Issue, PR Template 작성 
- [x] 피드백 내용 반영 
- [x] DB 데드락에 대한 공부 
- [x] Cooking 프로젝트 API 문서화 

### 기타
<hr>

<br/>

### Reference 
<hr>

- 깃 Issue, pr 템플릿 
https://amaran-th.github.io/Github/[Github]%20Issue%20&%20PR%20Template%20설정하기/

- CI 구축 
https://jh-labs.tistory.com/416
