### ISSUE TITLE
[Dev] 다대일 연관관계 순환 참조 문제 발생 해결 

### ISSUE THREAD

**Issue by Bumnote** [Bumnote/catchTable#18]
### 📝 작업 내용 및 설명 
<hr>

다대일 연관관계를 맺으면서, N측 엔티티에 존재하는 1측 엔티티 정보까지 함께 출력되는 상황이 발생했습니다. 이를 해결하기 위해서 다음과 같은 작업을 수행합니다.

### ✔️ TO-DO
<hr>

- [x] findById -> findByRestaurant 수정 
- [x] QueryDsl 활용하여 중복 질의가 아닌 1번의 질의 수행 
- [x] DTO를 활용하여 1측 엔티티 정보 삭제 

### 기타
<hr>

### Reference 
<hr>
