### ISSUE TITLE
[Dev] 불필요한 코드 및 함수, 클래스명 리팩토링 

### ISSUE THREAD

**Issue by Bumnote** [Bumnote/catchTable#21]
### 📝 작업 내용 및 설명 
<hr>
전체적으로 불필요한 코드, 어노테이션 제거하고, 함수명 그리고 클래스명을 상황에 맞게 변경합니다. 
또한, Argument Resolver 에 대해서 학습하고 구현합니다.

### ✔️ TO-DO
<hr>

- [x] Argument Resolver 구현 
- [x] 불필요한 코드 및 어노테이션 제거 
- [x] 상황에 맞게 함수명, 클래스명 변경
- [x] SessionCreationPolicy.STATELESS 개념 학습 
- [x] salt 개념 학습

### 기타
<hr>

### Reference 
<hr>

- https://velog.io/@yoosj97/암호화-기법-해시Hash-솔트Salt
- https://eastc.tistory.com/entry/Spring-Argument-Resolver-내부-구경-하기
- https://www.inflearn.com/community/questions/34886/jsessionid의-생성에-대해서?srsltid=AfmBOoqc6fmfwqDxydc_wPqI76awPgXIL_QpTgVu5JMSanIu4XG-D1Ie
