### ISSUE TITLE
[Dev] 불필요한 코드 제거 및 Annotation 기반 인증 구현 

### ISSUE THREAD

**Issue by Bumnote** [Bumnote/catchTable#24]
### 📝 작업 내용 및 설명 
<hr>

1. 불필요한 디버깅용 로그를 삭제합니다. 어떤 값이 들어있는지 로그를 찍어보고 싶다면 테스트 과정에서 확인하고, 확인이 되었다면 가동성을 해치지 않도록 지워줍니다. 
2. URI 기반으로 유저의 역할(role)을 인증하는 방식에서 Annotation 기반 인증 방식으로 기능을 수정합니다. 
3. Argument Resolver 구현에서 Controller 매개변수에 있는 @UserArg 어노테이션 없이도 작동할 수 있도록 수정합니다.

### ✔️ TO-DO
<hr>

- [x] 불필요한 디버깅용 로그 코드 삭제 
- [x] Annotation 기반 인증 방식 구현
- [x] Argument Resolver 가독성 개선
- [x] Jwt 토큰에 객체를 넣고, 객체를 꺼내 사용함으로써 DB 접근량 감소

### 기타
<hr>

### Reference 
<hr>
